import java.util.ArrayList;
import java.util.Scanner;

public class RunNeuralNetwork
{
    //features
    private static NeuralNetwork neuralNetwork = new NeuralNetwork ( );
    private static Scanner userScanner = new Scanner ( System.in );
    
    //constructor
    public static void main ( String [ ] arguments )
    {
        doTraining ( );
        
        doTesting ( );
    }
    
    public static void doTraining ( )
    {
        for ( int tDI = 0; tDI < getTrainingData ( ).size ( ); tDI ++ )
        {
            String rawInputLine = getTrainingData ( ).get ( tDI ).split ( ":" ) [ 0 ];
            String rawInputs [ ] = rawInputLine.split ( "," );
            int inputs [ ] = new int [ ] { Integer.parseInt ( rawInputs [ 0 ] ), Integer.parseInt ( rawInputs [ 1 ] ) };
            neuralNetwork.doForwardPropagation ( inputs );
            
            
            String targetLine = getTrainingData ( ).get ( tDI ).split ( ":" ) [ 1 ];
            neuralNetwork.doBackwardPropagation ( Integer.parseInt ( targetLine ) );
        }
    }
    
    public static void doTesting ( )
    {
        System.out.println ( "Neural network practice January 2020" );
        System.out.println ( "1. Get neural network guess from input = (0,0)" );
        System.out.println ( "2. Get neural network guess from input = (0,1)" );
        System.out.println ( "3. Get neural network guess from input = (1,0)" );
        System.out.println ( "4. Get neural network guess from input = (1,1)" );
        System.out.println ( "5. Get me out of here!" );
        System.out.println ( "\nSelect an item" );
        
        int userOption = userScanner.nextInt ( );
        
        switch ( userOption )
        {
            case 1:
            {
                int inputs [ ] = new int [ ] { 0, 0 };
                neuralNetwork.doForwardPropagation ( inputs );
                System.out.println ( "Neural network guess at input: 0, 0 = " + neuralNetwork.getOutcome ( ) );
                returnToTesting ( );
            }
            break;
            
            case 2:
            {
                int inputs [ ] = new int [ ] { 0, 1 };
                neuralNetwork.doForwardPropagation ( inputs );
                System.out.println ( "Neural network guess at input: 0, 1 = " + neuralNetwork.getOutcome ( ) );
                returnToTesting ( );
            }
            break;
            
            case 3:
            {
                int inputs [ ] = new int [ ] { 1, 0 };
                neuralNetwork.doForwardPropagation ( inputs );
                System.out.println ( "Neural network guess at input: 1, 0 = " + neuralNetwork.getOutcome ( ) );
                returnToTesting ( );
            }
            break;
            
            case 4:
            {
                int inputs [ ] = new int [ ] { 1, 1 };
                neuralNetwork.doForwardPropagation ( inputs );
                System.out.println ( "Neural network guess at input: 1, 1 = " + neuralNetwork.getOutcome ( ) );
                returnToTesting ( );
            }
            break;
            
            case 5:
                System.exit ( 0 );
            break;
        }
    }
    
    public static void returnToTesting ( )
    {
        userScanner.nextLine ( );
        userScanner.nextLine ( );
        System.out.println ( "\f" );
        doTesting ( );
    }
    
    
    
    
    
    
    
    
    
    public static ArrayList <String> getTrainingData ( )
    {
        ArrayList <String> returnValue = new ArrayList <String> ( );
        
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,1:0");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "0,0:0");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        returnValue.add ( "1,0:1");
        returnValue.add ( "0,1:1");
        
        return returnValue;
    }
}